global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['https://api.ryan.pixicode.dev/']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        source_labels: [__param_target]
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'portfolio'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['https://ryan.pixicode.dev/']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        source_labels: [__param_target]
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
